name: hk

permissions: {}

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: hugoh/gh-workflows/setup@3491144ab533d5d7724af1975dc694c59c9db0d6 # v1.10.0
      - uses: hugoh/gh-workflows/hk-check@3491144ab533d5d7724af1975dc694c59c9db0d6 # v1.10.0
        env:
          PINACT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
